# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('phone3', models.IntegerField()),
                ('phone4', models.IntegerField()),
                ('phone5', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_number_in_box',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchases_count',
            field=models.IntegerField(),
        ),
    ]
