# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180216_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=1000, verbose_name='Тип яйца')),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone1',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone2',
            field=models.IntegerField(blank=True, verbose_name='Телефон2 не обязательный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone3',
            field=models.IntegerField(blank=True, verbose_name='Телефон3 не обязательный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone4',
            field=models.IntegerField(blank=True, verbose_name='Телефон4 не обязательный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone5',
            field=models.IntegerField(blank=True, verbose_name='Телефон5 не обязательный'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Type', verbose_name='Тип яйца'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_name',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_number_in_box',
            field=models.IntegerField(blank=True, verbose_name='Количество в ящике'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_photo_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_price',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Цена (пр: 6,4)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_weight',
            field=models.IntegerField(blank=True, verbose_name='Средний вес'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchases_count',
            field=models.IntegerField(blank=True, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchases_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата и время покупки'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchases_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchases_summ',
            field=models.FloatField(blank=True, max_length=1000000, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='usersinsite',
            name='user_fio',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='usersinsite',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersinsite',
            name='user_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='usersinsite',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='usersinsite',
            name='user_purchase',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Purchases', verbose_name='Покупка'),
        ),
    ]
