# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180216_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='curs',
            field=models.CharField(blank=True, max_length=50, verbose_name='Курс доллара'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='min_summ_order',
            field=models.CharField(blank=True, max_length=50, verbose_name='Минимальная сумма заказа'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone1',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон2 не обязательный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон3 не обязательный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон4 не обязательный'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон5 не обязательный'),
        ),
    ]
